/* eslint-disable class-methods-use-this */
import axios from "axios"
import { createHandler, Get, Query } from "next-api-decorators"
import { ethers } from "ethers"

const getAddress = async (address?: string) => {
  if (!address) return null
  if (ethers.utils.isAddress(address)) return address
  const provider = new ethers.providers.AlchemyProvider(1, process.env.ALCHEMY_API_KEY)
  return provider.resolveName(address)
}
class Mint {
  @Get()
  async mint(
    @Query("name") name?: string,
    @Query("description") description?: string,
    @Query("imageUri") imageUri?: string,
    @Query("recipient") recipient?: string,
  ) {
    try {
      const reesponse = await axios.post(process.env.DEFENDER_AUTOTASK_WEBHOOK, {
        name: name || "nft name generator",
        description: description || "generated by ChillRx",
        imageUri:
          imageUri ||
          "ipfs://bafybeidyqy7n2defa767w64g4oj4n63whgfl7mtigwqq6co3i6kg4qlo5u/lilnoun-6473.png",
        recipient: (await getAddress(recipient)) || "0x181e81e32c9Abc0E1ba637034D8F9ac97F8547Ea",
      })
      const txReceipt = JSON.parse(reesponse.data.result).hash
      return { txReceipt }
    } catch (err) {
      throw new Error(err)
    }
  }
}
export default createHandler(Mint)
